### ISSUE TITLE
Ошибка в классе Translit

### ISSUE THREAD

**Issue by kazip** [Andre-487/php_rutils#26]
Warning: preg_replace(): Compilation failed: invalid range in character class at offset 9 in php_rutils/Translit.php on line 114

В строке 114 файла Translit.php :
<code>$inString = preg_replace('/[—−-\s\t]+/u', '-', $inString);</code>
Нужно заэкранировать символ "-"  - получится так:
<code>$inString = preg_replace('/[—−\\-\s\t]+/u', '-', $inString);</code>

**Comment by Andre-487** [comment]
Действительно. Не получится сделать pull request?

**Comment by Andre-487** [comment]
Исправлено в #27
